### ISSUE TITLE
no gui menus in *nix version

### ISSUE THREAD

**Issue by xeverse** [toddcarnes/Astrolog-64#2]
This can't be done with the current code. Can it..

**Comment by toddcarnes** [comment]
As of right now, the Linux version is command-line only. There is some interaction with X Windows available, depending on what switches you have set, but no actual GUI is available.

It's interesting that you brought this up at this time. I have only just begun my own branch of the code to convert over to Qt so that astrolog will be able to have a nice GUI on **all** OS that it runs on (Windows, Mac, Linux, etc.).

Conversion to Qt will have the added benefits of allowing for simplification of the code base and will make it easier to supply translations of the program to other languages.

**Comment by toddcarnes** [comment]
I've realized that despite my good intentions, I just don't have the time or resources to do this. So, I've un-assigned myself and added the help wanted tag.

**Comment by xeverse** [comment]
leastwise thx for good intentions..
